name: Build and Deploy to Render

on: [push]

jobs:
  build:
    environment:
      name: Testing
    env:
      DB_NAME: ${{secrets.DB_NAME}}
      DB_HOSTNAME: ${{secrets.DB_HOSTNAME}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      TOKEN_EXPIRY: ${{secrets.TOKEN_EXPIRY}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup Pip
        run: python -m pip install --upgrade pip
      - name: Install Project Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests with PyTest
        run: pytest -sxv --disable-warnings
